#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

if [[ ! -f "$SCRIPT_DIR"/colors.bash ]]; then
  "$SCRIPT_DIR"/generate
fi

# shellcheck source=colors.bash
source "$SCRIPT_DIR"/colors.bash

colors=(
  BLACK
  RED
  GREEN
  YELLOW
  BLUE
  PURPLE
  CYAN
  WHITE
  GREY
)

print_colors() {
  local prefix=${1:-}
  local key
  for c in "${colors[@]}"; do
    key=${prefix}${c}
    [[ ! -v $key ]] && continue
    echo -e "- ${!key}${prefix}${c}${RESET_ALL}"
  done
}

printf '\n%s\n' '[General Foreground Colors]'
print_colors
printf '\n%s\n' '[General Background Colors]'
print_colors BG_
printf '\n%s\n' '[Bold Colors]'
print_colors BOLD_
printf '\n%s\n' '[Underline Colors]'
print_colors UL_
printf '\n%s\n' '[Blink Colors]'
print_colors BLK_
printf '\n%s\n' '[Reverse Colors]'
print_colors REV_
printf '\n%s\n' '[Bright Colors]'
print_colors BRI_
printf '\n%s\n' '[Bright & Bold Colors]'
print_colors BRI_BOLD_
